[[mgr.prepend_keymap]]
on   = "E"
run  = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin eza-preview inc-level"
desc = "Increment tree level"

[[mgr.prepend_keymap]]
on   = "_"
run  = "plugin eza-preview dec-level"
desc = "Decrement tree level"

[[mgr.prepend_keymap]]
on   = "$"
run  = "plugin eza-preview toggle-follow-symlinks"
desc = "Toggle tree follow symlinks"

[[mgr.prepend_keymap]]
on   = "*"
run  = "plugin eza-preview toggle-hidden"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on   = "m"
run  = "plugin bookmarks save"
desc = "Save current postion as a bookmark"

[[mgr.prepend_keymap]]
on   = "'"
run  = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "d" ]
run  = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "D" ]
run  = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = [ "P", "s" ]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = [ "P", "l" ]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = [ "P", "P" ]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = [ "P", "d" ]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = [ "P", "D" ]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = [ "P", "m" ]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = [ "P", "M" ]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

[[mgr.prepend_keymap]]
on   = "1"
run  = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "2"
run  = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "3"
run  = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "4"
run  = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "5"
run  = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "6"
run  = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "7"
run  = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "8"
run  = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on   = "9"
run  = "plugin relative-motions 9"
desc = "Move in relative steps"

